### ISSUE TITLE
Agree upon the structure of the dataset

### ISSUE THREAD

**Issue by viol37** [TeamPML/GuthubSecurityIssues#1]
Suggestion is to store name, labels, and description of each issue. Maybe something else?

**Comment by datapaf** [comment]
We may later save the useful data in .csv

**Comment by datapaf** [comment]
@eyihluyc Can you add the description of the columns in the dataset?

**Comment by viol37** [comment]
added [here](https://github.com/TeamPML/GuthubSecurityIssues/blob/main/data/security_issues.csv) in security issues
